on: workflow_dispatch

name: test-tweet

jobs:
  test-tweet-post:
    
    runs-on: macOS-latest
    
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      STACK_EXCHANGE_KEY: ${{ secrets.STACK_EXCHANGE_KEY }}
    
    steps:
      - uses: actions/checkout@v2
  
      - uses: r-lib/actions/setup-r@v1
        with:
          r-version: 'release'
          use-public-rspm: true
  
      - uses: r-lib/actions/setup-r-dependencies@v1
      
      - name: Post tweets
        run: Rscript test-tweet.R
