on: workflow_dispatch
  # push:
  #   branches:
  #     - main
  # schedule:
  #   # run every 5 mintues
  #   - cron: '*/5 * * * *'

name: tidyversetweets-bot

jobs:
  tidyversetweets-bot-post:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      STACK_EXCHANGE_KEY: ${{ secrets.STACK_EXCHANGE_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
  
      - name: Setup R 
        uses: r-lib/actions/setup-r@master
        with:
          use-public-rspm: true
          
      - name: R dependencies
        uses: r-lib/actions/setup-r-dependencies@v1
        with:
          cache-version: 2

      - name: Post tweets
        run: Rscript tidyversetweets.R
